/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package adventofcode2020

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
    val fr = FileReader()
    val nums = fr.doWork(args[0])
    val num = findTheGoose(nums)
    println(num)
}
