/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package adventofcode2020

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
    // offer what day we are trying to solve
    println("What day are you on?")
    val day = readLine()
    println("What part are you solving?")
    val part = readLine()

//    println(day)
//    println(part)

    TODO("Fix command line interaction")

//    val fr = FileReader(args[0])
//    val lines = fr.lines()
//    val tp = TupleParser(lines)
//    val count = tp.count()
//    println(count)
}
