/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package adventofcode2020

import kotlin.test.Test

class ResourceTest {
    @Test fun testResourceHasAGreeting() {
        //   val classUnderTest = Resource("")
        //   assertNotNull(classUnderTest.resource(), "app should have a greeting")
    }
}
